POST http://localhost:8080/auth/realms/fincycle/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest
&client_secret=
&grant_type=
&username=
&password=

###

GET http://localhost:3000/transactions
Authorization: Bearer 
###

POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer 

{
    "payment_date": "2021-01-02",
    "name": "Nova Conta 3",
    "description": "Descricao",
    "category": "category1",
    "amount": 40,
    "type": "debit"
}

###

POST http://localhost:3000/transactions
Content-Type: application/json

{

}

###

GET http://localhost:3000/accounts
Content-Type: application/json

{
    "name": "Account 1",
    "subdomain": "tenant1"
}

###

POST http://localhost:3000/accounts
Content-Type: application/json

{
    "name": "Account 2",
    "subdomain": "tenant2"
}

###

GET http://localhost:3000/reports
Authorization: Bearer

###
POST http://localhost:3000/reports
Authorization: Bearer 
Content-Type: application/json

{
    "start_date": "2021-01-02",
    "end_date": "2021-05-01"
}